### ISSUE TITLE
Crashing when starting in a real-world client

### ISSUE THREAD

**Issue by MoriTanosuke** [MoriTanosuke/nadiamiona#12]
The mod crashes when started in a real-world client with other mods. Running from IDE is fine though.

````
---- Minecraft Crash Report --

WARNING: coremods are present:
  FMLPlugin (InventoryTweaks-1.60-40.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 14.01.17 23:57
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoSuchMethodError: kalle.tools.ItemPickaxeEmerald.setUnlocalizedName(Ljava/lang/String;)Lnet/minecraft/item/Item;
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:162)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:739)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:310)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:495)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchMethodError: kalle.tools.ItemPickaxeEmerald.setUnlocalizedName(Ljava/lang/String;)Lnet/minecraft/item/Item;
	at kalle.tools.ItemPickaxeEmerald.<init>(ItemPickaxeEmerald.java:10)
	at kalle.proxies.BasisCommonProxy.preInit(BasisCommonProxy.java:41)
	at kalle.proxies.BasisClientProxy.preInit(BasisClientProxy.java:7)
	at kalle.Basis.preInit(Basis.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:737)
	... 10 more


A detailed walkthrough of the error, its code path and all known details is as follows:
-------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 7 (amd64) version 6.1
	CPU: 4x Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz
	Java Version: 1.8.0_05, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 90891288 bytes (86 MB) / 381681664 bytes (364 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.1902 Optifine OptiFine_1.8.9_HD_U_H3 10 mods loaded, 10 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1902-1.8.9.jar) 
	UCHI	Forge{11.15.1.1902} [Minecraft Forge] (forge-1.8.9-11.15.1.1902-1.8.9.jar) 
	UCHI	BiblioCraft{2.0.1} [BiblioCraft] (BiblioCraft[v2.0.1][MC1.8.9].jar) 
	UCHI	cfm{4.0.1} [MrCrayfish's Furniture Mod] (cfm-4.0.1-mc1.8.9.jar) 
	UCHI	thebombzenapi{2.5.2} [ThebombzenAPI] (ThebombzenAPI-v2.5.2-mc1.8.9.jar) 
	UCHI	enchantview{5.0.1} [EnchantView] (EnchantView-v5.0.1-mc1.8.9.jar) 
	UCHI	inventorytweaks{1.60-40-e06e29a} [Inventory Tweaks] (InventoryTweaks-1.60-40.jar) 
	UCHI	JEI{2.28.18.186} [Just Enough Items] (jei_1.8.9-2.28.18.186.jar) 
	UCHE	kalle{0.0.3} [Nadiamiona] (nadiamiona-1.8.9-3.jar) 
	Loaded coremods (and transformers): 
FMLPlugin (InventoryTweaks-1.60-40.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 376.33' Renderer: 'GeForce GTX 660/PCIe/SSE2'
	OptiFine Version: OptiFine_1.8.9_HD_U_H3
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 376.33
	OpenGlRenderer: GeForce GTX 660/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4
````

**Comment by MoriTanosuke** [comment]
Strange, rebuild on Linux and started with forge *11.15.1.1902*

![minecraft 1 8 9_011](https://cloud.githubusercontent.com/assets/105346/22148045/2dfdf218-df0c-11e6-9851-73b878edb0bd.png)

Maybe it is related to the other mods or a windows issues. Will rebuild and start later on Windows.

**Comment by MoriTanosuke** [comment]
@Flyrija Kannst Du nochmal dieses JAR probieren? Evtl ist mein letzter Upload nicht *reobfuscated*...

[nadiamiona-1.8.9-4.jar.zip](https://github.com/MoriTanosuke/nadiamiona/files/719230/nadiamiona-1.8.9-4.jar.zip)

**Comment by Flyrija** [comment]
Okay, es läuft, aber da haben sich einige Käfer breitgemacht.

- Weiße Wolltreppen sind zwar drin, haben aber kein Rezept. Funktionieren aber prima soweit ich sehe.
- es sind Wollmauern drin?  
- Bei Emerald Hoe, Shovel, Pickaxe und Axe sollten die Stickys durch Diamanten ersetzt werden. (War so gedacht weil sie solange halten wie Diamantzeug, aber die Enchants von Goldtools nutzen) - kann aber auch so bleiben =)
- Die Emerald Battleaxe fehlt. 
- Emerald Sword hat keinen Itemnamen (item.EmeraldSword.name).
- Sandstone Wall steht als Red Sandstone Wall drin.
- Lapis Crate hat als Rezept: Crate + Ink Sack ..oO?
- Salmon Crate fehlt komplett.
- Bücherregale in Akazie und Dark Oak haben keinen Namen und kein Rezept. (Stehen mit Birke im Rezept drin)
- Bright Parquet Floor und Dark Parquet Floor sind zuviel drin, können raus.
- Theken: Rezept ist bei allen etwas falsch, als Menge sollten 2-3 rauskommen bei den Mats die man braucht, im moment bekommt man 1 stk.
- - - <- planks
x x x <- full blocks  wäre richtig, drin ist aber

o - - 
- x x
..wobei die Mats durcheinander geraten sind. 
- Jungle Bar hat das Rezept der Birch Bar drin.
- Acacia Bar hat das Rezept der Jungle Bar drin.
- Birch Bar hat das Rezept der Acacia Bar. 
- Salmon Sandwich hat den cooked fish statt dem cooked salmon im rezept
- Fish Sandwich fehlt.

Uffz, mehr fällt mir im Moment nicht ein/auf. Danke das du dir soviel Mühe und Arbeit machst.

**Comment by MoriTanosuke** [comment]
Hm, da muss ich nochmal gucken. Kann sein, dass ich das JAR auf einem Branch bei mir gebaut habe. Die Wollsachen waren ja erstmal nur ein Experiment.

Die anderen Dinge guck ich mir nochmal an.

**Comment by MoriTanosuke** [comment]
* Sticks durch Diamanten ersetzt
* Rezept für Battle Axe ist nicht im PDF
* `item.EmeraldSword.name` als *Emerald Sword* eingefügt
* `item.sandstone_wall.name` und `tile.sandstone_wall.name` in *Sandstone Wall* korrigiert
* Lapiskiste nutzt jetzt Lapis, hatte keine Meta ID angegeben - das ist nämlich auch ein Dye, siehe http://minecraft.gamepedia.com/Data_values#Dyes :roll_eyes: 
* Fischkiste nutzt jetzt auch die richtige Meta ID für Lachs statt normalem rohen Fisch
* Meta IDs der Holzkisten korrigiert, siehe http://minecraft.gamepedia.com/Data_values#Wood_Planks
* Sandwich nutzt jetzt Meta ID von Lachs statt normalem rohen Fisch
* Fisch Sandwich eingefügt

Nochmal testen bitte.

[nadiamiona-1.8.9-4.jar.zip](https://github.com/MoriTanosuke/nadiamiona/files/719606/nadiamiona-1.8.9-4.jar.zip)

**Comment by MoriTanosuke** [comment]
Gerade nochmal selbst getestet:

- *Bright parquet floor* hat kein Rezept
- *Dark parquet floor* hat kein Rezept
- *Acacia Bookshelf* hat keinen Namen *tile.BooksAcacia.name*
- *Acacia Bookshelf* wird mit Birch statt Acacia gebaut
- *Dark Oak Bookshelf* hat keinen Namen *tile.BooksDarkOak.name*
- *Dark Oak Bookshelf* wird mit Birch statt Dark Oak gebaut
- *Crate of Lapislazuli* hat nur Rezept mit Crate, nicht mit Planks
- *Wool Wall* hat keinen Namen *tile.wool_wall.name*
- *Hedge* ist grau statt grün
- *Wool Stairs* hat kein Rezept
- *Small block* hat kein Rezept

**Comment by Flyrija** [comment]
- Bright parquet floor hat kein Rezept
- Dark parquet floor hat kein Rezept
die beiden sind auch überflüssig, sind ja schon 6 Parkettsorten drin.  Wahrscheinlich nen Relikt aus der alten Version wo es nur 2 Sorten gab.

- Wool Wall hat keinen Namen tile.wool_wall.name
Wool Wall braucht man eigentlich nicht, es sei denn, man will gepolsterte Säulen haben =)

- Hedge ist grau statt grün 
nur im Inventar, aufgestellt ist sie grün.

Bin noch nicht neu zum Testen bekommen, schaue das ich morgen die Version anwerfe und mal schaue was geht und was nicht.

**Comment by MoriTanosuke** [comment]
Ok, the original issue is resolved. The JAR was not re-obfuscated. I will remove the prior release and the next one will be re-obfuscated and runnable.

Missing recipes are done in existing issue #3
